name: Build BypassDomain
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: |
          upstreamLatestTag=$(curl -sSL --connect-timeout 5 --retry 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/gfwlist/gfwlist/commits | grep "date"| cut -d\" -f4 | head -n 1 |sed 's/[^0-9]*//g')
          thisLatestTag=$(curl -sSL --connect-timeout 5 --retry 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "tag_name" | cut -d\" -f4)
          if [[ $upstreamLatestTag != $thisLatestTag ]]; then
            echo "NeedToSync=true" >> $GITHUB_ENV
          fi
          echo "RELEASE_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          echo "TAG_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          
      - name: Checkout codebase
        uses: actions/checkout@v4       
          
      - name: Generate Domain List
        if: ${{ env.NeedToSync }}
        run: |
          curl -L https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt | base64 -d > gfwlist.txt
          grep -E '^([|]{2}|[.])' gfwlist.txt  | grep -v '/' | grep -v '[*]' | grep -vE '([0-9]{1,3}\.){3}[0-9]{1,3}' | sed 's/^[|.]*//' | sort -u > BypassList.txt

      - name: Generate Reject file
        if: ${{ env.NeedToSync }}
        run: |
          curl -L https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdnslite.txt > ./AdList.txt
          grep -v '^@@' ./AdList.txt | grep '||' | sed s/^||//; s/\^$//' > ./Reject.txt

      - name: Git push file to branch
        if: ${{ env.NeedToSync }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./BypassList.txt
          git add ./Reject.txt
          git commit -m "${{ env.RELEASE_NAME }}"
          git push -f
