name: Build BypassDomain
on:
  workflow_dispatch:
  schedule:
    - cron: "30 21 * * *"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: |
          version=$(date +'%Y%m%d%H%M%S')
          echo "RELEASE_NAME=$version" >> $GITHUB_ENV
          echo "TAG_NAME=$version" >> $GITHUB_ENV
          
      - name: Checkout codebase
        uses: actions/checkout@v4
          
      - name: Fetch GFWList
        run: |
          curl -L https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt | base64 -d > gfwlist.txt
          
      - name: Format Domain List
        run: |
          grep -E '^([|]{2}|[.])' gfwlist.txt  | grep -v '/' | grep -v '[*]' | sed 's/^[|.]*//' | sort -u > domain.txt
          cat ./Custom.txt >> ./domain.txt
          sed 's/^/[\//g;s/$/&\/]10.10.10.11/g' ./domain.txt > ./BypassList.txt
          echo "10.10.10.1" >> ./BypassList.txt

      - name: Generate AdguardHome file
        run: |
          curl -L https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt > ./AdList.txt
          grep '||' ./AdList.txt > ./AdguardHome.txt

      - name: Git push file to branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./BypassList.txt
          git add ./AdguardHome.txt
          git commit -m "${{ env.RELEASE_NAME }}"
          git push -f

      - name: Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./BypassList.txt
            ./AdguardHome.txt
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
