name: Build BypassDomain
on:
  workflow_dispatch:
  schedule:
    - cron: "30 21 * * *"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compare latest tags and set variables
        run: |
          upstreamLatestTag=$(curl -sSL --connect-timeout 5 --retry 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/v2fly/domain-list-community/releases/latest | grep "tag_name" | cut -d\" -f4)
          thisLatestTag=$(curl -sSL --connect-timeout 5 --retry 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "tag_name" | cut -d\" -f4)
          if [[ $upstreamLatestTag != $thisLatestTag ]]; then
            echo "NeedToSync=true" >> $GITHUB_ENV
          fi
          echo "RELEASE_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          echo "TAG_NAME=$upstreamLatestTag" >> $GITHUB_ENV
        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@v4
        if: ${{ env.NeedToSync }}
        with:
          path: code

      - name: Checkout v2fly/domain-list-community
        if: ${{ env.NeedToSync }}
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community

      - name: Setup Go
        uses: actions/setup-go@v5
        if: ${{ env.NeedToSync }}
        with:
          go-version-file: domain-list-community/go.mod

      - name: Get dependencies and run
        if: ${{ env.NeedToSync }}
        run: |
          cd domain-list-community || exit 1
          go run ./ -exportlists=$(cat ../code/domain)
          cd ../

      - name: Format Domain List
        if: ${{ env.NeedToSync }}
        run: |
          cd domain-list-community || exit 1
          cat *.txt | grep domain | sed 's/domain://g' | sed 's/:@cn//g' | sed 's/:@ads//g' | sed 's/:@!cn//g' | sort -u > domain.txt
          cp domain.txt ../code/
          cd ../code/
          cat ./Custom.txt >> ./domain.txt
          sed 's/^/[\//g;s/$/&\/]10.10.10.11/g' ./domain.txt > ./BypassList.txt
          echo "10.10.10.1" >> ./BypassList.txt
          cd ../

      - name: Generate AdguardHome file
        if: ${{ env.NeedToSync }}
        run: |
          cd code || exit 1
          curl https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt > ./AdList.txt
          grep '||' ./AdList.txt > ./AdguardHome.txt
          cd ../

      - name: Git push assets to "release" branch
        if: ${{ env.NeedToSync }}
        run: |
          cd code || exit 1
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./BypassList.txt
          git add ./AdguardHome.txt
          git commit -m "${{ env.RELEASE_NAME }}"
          git push -f

      - name: Release and upload assets
        if: ${{ env.NeedToSync }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./code/BypassList.txt
            ./code/AdguardHome.txt
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
