name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    
    - name: Fetch files
      run: |
        curl https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf > ./ChinaList.conf
        curl https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt > ./GFW.txt
        curl https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt > ./AdguardHome.txt
        
    - name: Format & Custom
      run: |
        sed 's/server=\//\[\//g;s/114.114.114.114/\]10.10.10.1/g' ./ChinaList.conf > ./ChinaList.txt
        echo "10.10.10.11" >> ./ChinaList.txt
        sed 's/^/[\//g;s/$/&\/]10.10.10.11/g' ./GFW.txt > ./GFWList.txt
        echo "10.10.10.1" >> ./GFWList.txt
        grep '||' ./AdguardHome.txt > ./AdList.txt
        
    - name: Push commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
